### PR TITLE
Reword “Goals” Section of Readme

### PR DESCRIPTION
**Pull request by RageGamerBoi**
I noticed the goals section of the readme could use some rewording/revision.

If there’s anything that I changed that misses the mark, feel free to edit it and tell me why. I know enough about this project to know these needed to be changed a little, but not enough to be 100% confident.

Thanks :)

Edit: To best see what I changed, look at the first commit before I re-alphabetized the list.

### CODE REVIEW

**Comment by garsipal** [comment]
Hey there, thank you for your contribution, the readme is a bit lacking in general.

I may sound nitpicky, I know, but I need to point out a few small things:    

- `Depth: Create simple yet convincing lore to give the game's universe a story with depth and realism.`
I don't think "realism" quite fits the bill here, I'd go with "believability" or another word that has the same value. Lore has to be believable but not quite realistic, which would also be in light conflict with the `Vibrant Atmosphere` goal.


- `Immersion: Implement audio, effects, and gunplay on par with modern standards. `
Personally I'd keep it just a bit more down-to-earth, of course we _try_ to catch up with modern standards but we're not an AAA studio. 😄 

- Just one more thing, even though it's the least relevant, it's usually unnecessary to capitalize the first letter after a colon. 😛 

Other than these it's good to go, thanks!

**Comment by RageGamerBoi** [comment]
I think lore doesn’t necessarily have to be believable, just make sense, I meant more ‘realistic for the game’.
I’ve changed it to “give the game a sense of purpose” as that seems to be more what the goal of the lore is in relation to the game.

I’ve changed the Immersion section to say ‘bring x, y, and z *closer* to modern standards’ which has the same effect but without angering Yoda.

I just used AP’s styleguide for the ending punctuation so capitalization is necessary (I think… https://www.instructionalsolutions.com/blog/bulleted-list-punctuation)

**Comment by garsipal** [comment]
But a colon is used to clarify a point, to expand on a matter, and it's not ending punctuation. 🤔

**Comment by RageGamerBoi** [comment]
Ah, sorry I misunderstood. According to the article I sent, "I do not recommend this 'vertical lists punctuated as a sentence' format with semicolons for business writing. It’s visually cluttered, impeding easy scan. While it’s not wrong and some style guides recommend this, it’s not the best business writing choice."
I replaced the semicolons with periods and made the goals proper sentences for professionalism, if you want I can change it back.

**Comment by RageGamerBoi** [comment]
On a quick re-read I actually slightly misapplied the formatting, let me fix that.

**Pull request merged**
