### PR TITLE
Show client num in scoreboard

### PR DESCRIPTION
**Pull request by Jed-**
Correctly show client number in the scoreboard when the player has master or `showclientnum` is set to 1

### CODE REVIEW

**Comment by coornio** [comment]
Implying it's incorrectly showing it :P 

The scoreboard wasn't meant to show client IDs. Any management should take place from the CCI interface which, iirc, is bound to F1. Should still work I believe, even if placeholder.

**Comment by Jed-** [comment]
I mean, the setting was already there so I expected it to work. Having all the information in one place is convenient.

**Comment by Jed-** [comment]
Some of us prefer to use commands, it's good to have a choice. I agree that it should be disabled by default. There is already a "cn.png" icon so I went with that and I think it looks good.

**Comment by coornio** [comment]
Oh neat, I thought I had gotten rid of that. Granted, it looks like the C-sharp symbol which was a point of concern initially :D

**Comment by garsipal** [comment]
It will always be C-sharp to me. ¯\_(ツ)_/¯

**Comment by coornio** [comment]
Pushed own changes to implement the cn cell in the scoreboard, only appears if showclientnum is enabled. As for the execident, I'd vote to have it when authentication status changes, whether lost or gained. We will distinguish which of the two on the cubescript side for anything needed, the flexibility is preferable.

**Comment by Jed-** [comment]
I'm closing this now that similar changes have been pushed.

**Pull request closed without merging**
