### PR TITLE
Bring back the minimap in CTF

### PR DESCRIPTION
**Pull request by Jed-**
Add a `uiminimap` widget that renders the minimap background in the UI

The radar icons are placed with cubescript

The minimap texture can be manipulated with the `hudminimap` shader

### CODE REVIEW

**Comment by garsipal** [comment]
This is quite some work. Nice!
I'm waiting for further progress before saying anything more here.

**Comment by garsipal** [comment]
Got a few questions so far.
- Why are you commenting out `if(lookupshaderbyname(name)) return;` on shader.cpp?
- Why is there an empty boolean function in the `Minimap` structure in ui.cpp (`target()`)?

**Comment by Jed-** [comment]
> Why are you commenting out if(lookupshaderbyname(name)) return; on shader.cpp?
This allows the `hudminimap` shader to be reloaded when `minimapalpha` changes, so that transparency can be applied.

> Why is there an empty boolean function in the Minimap structure in ui.cpp (target())?
This has been addressed on Discord.

**Comment by garsipal** [comment]
Latest changes uncomment the previously mentioned condition on `shader`, avoiding unintended consequences.

**Pull request merged**
